### ISSUE TITLE
RuntimeError: Given groups=1, weight of size [32, 2, 5, 5], expected input[7, 4, 260, 260] to have 2 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by wangdf90** [antoine-spahr/SN-PatchGAN_FreeForm-Inpainter#1]
can you help me?
INFO:root:No Checkpoint found. Training from beginning.
INFO:root:Start training the inpainting SN-PatchGAN.
Traceback (most recent call last):
  File "SNPatchGAN_scripts.py", line 182, in <module>
    main(config_path)
  File "SNPatchGAN_scripts.py", line 131, in main
    gan_model.train(train_dataset, checkpoint_path=os.path.join(out_path, 'Checkpoint.pt'),
  File "/home/wdf/workspace/SN-PatchGAN_FreeForm-Inpainter-main/code/src/models/optim/SNPatchGAN.py", line 157, in train
    fake_im2, fake_im1 = self.generator(im, mask)
  File "/home/wdf/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wdf/workspace/SN-PatchGAN_FreeForm-Inpainter-main/code/src/models/networks/InpaintingNetwork.py", line 707, in forward
    coarse_inpaint = self.coarse(input)
  File "/home/wdf/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wdf/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/wdf/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wdf/workspace/SN-PatchGAN_FreeForm-Inpainter-main/code/src/models/networks/InpaintingNetwork.py", line 148, in forward
    feat = self.conv_feat(x)
  File "/home/wdf/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/wdf/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/home/wdf/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 416, in _conv_forward
    return F.conv2d(F.pad(input, self._reversed_padding_repeated_twice, mode=self.padding_mode),
RuntimeError: Given groups=1, weight of size [32, 2, 5, 5], expected input[7, 4, 260, 260] to have 2 channels, but got 4 channels instead
@Fred-C-Wang @antoine-spahr

**Comment by antoine-spahr** [comment]
Hi ! Thanks for using my code ! 

From your error message, it seems you are using RGB images (3-channel images) without changing the config file accordingly. Indeed the default is to use grayscale images (note that there are +1 channels for the input of the models since you pass the mask of the region to inpaint as an additional channel). 

To fix the issue, try to change the values in your `SNPatchGAN_config.json` for the number of input channels : 
* `net.gen.in_channels` to 4 instead of 2
* `net.gen.out_channels` to 3 instead of 1 (because you get a RGB reconstruction)
* `net.dis.in_channels` to 4 instead of 2

Cheers!

**Comment by wangdf90** [comment]
Thank you very much！
if you add some introductions  of SNPatchGAN_config.json in README.md, it maybe help somebody
if you change some relative path to absolute path, it maybe good to debug

thanks again

**Comment by biel-wangdf3** [comment]
Thank you very much！
if you add some introductions  of SNPatchGAN_config.json in README.md, it maybe help somebody
if you change some relative path to absolute path, it maybe good to debug

thanks again
